name: app
description: "assistant of cycling"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  path: ^1.8.0
  xml: ^6.5.0
  fit_parser: ^2.0.0
  file_picker: ^9.1.0
  gpx: ^2.3.0
  build_runner: ^2.4.15
  sqflite: ^2.4.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
